### PR TITLE
Depends on vendored crates through newly created git-hosted wxrust-vendored-config crate

### LINKED ISSUE #162: Dependency on vendored repo blocks publishing
```
kenz@KENZnoMacBook-Air wx-base % cargo publish
    Updating crates.io index
error: all dependencies must have a version specified when publishing.
dependency `wx-universal-apple-darwin` does not specify a version
Note: The published dependency will use the version from crates.io,
the `git` specification will be removed from the dependency declaration.
```

### PR DESCRIPTION
**Pull request by kenz-gelsoft**
Closes #162

- Move dependencies on vendored repo out into another git repo crate https://github.com/kenz-gelsoft/wxrust-vendored-config
- This depends on following repos' PRs:
  - https://github.com/ancwrd1/wx-x86_64-pc-windows-gnu/pull/1
  - https://github.com/ancwrd1/wx-universal-apple-darwin/pull/1

---

TODO:
- [x] update README

### CODE REVIEW

**Comment by kenz-gelsoft** [comment]
@ancwrd1 Thank you for merging PRs.

BTW, as this run https://github.com/kenz-gelsoft/wxRust2/actions/runs/3001501843, 

Only mingw64 binaries can't be linked correctly, log: https://github.com/kenz-gelsoft/wxRust2/runs/8210817400?check_suite_focus=true

Are there any change on build toolchain for that binary?

**Comment by ancwrd1** [comment]
Uhm, this looks like a weird mix of gnu and msvc.

```
D:\a\wxRust2\wxRust2\target\x86_64-pc-windows-gnu\debug\deps\libwxrust_base-da3706a2162f51f6.rlib(manual.o): in function `wxMBConv::~wxMBConv()':

          C:/Users/runneradmin/.cargo/git/checkouts/wx-x86_64-pc-windows-msvc-2e8cedf9f53610ca/d822155/include/wx/strconv.h:173: undefined reference to `__imp__ZTV8wxMBConv'
```

**Comment by ancwrd1** [comment]
I've updated wxWidgets to 3.2.0, for -gnu version used  mingw gcc 12.2.0.

**Comment by kenz-gelsoft** [comment]
OK, I found the cause of this bustage.
This PR moves deps on vendored crates to *build-dependency*.

So platform specific dependency was based on the host's target. Currently CI for 
mingw64 build uses cross (toolchain) compiling this affected only the mingw64 build.

**Comment by kenz-gelsoft** [comment]
It seems to require the placeholder crate on the (runtime) dependency as I noted as an alternative approch in https://github.com/kenz-gelsoft/wxRust2/issues/162#issuecomment-1234921823 .

**Comment by kenz-gelsoft** [comment]
Build and README are fixed.

**Pull request merged**
